spring.application.name=forever-plan-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/forever_plan
spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.write-dates-as-timestamps=false
